- name: Install Golang with yum
  become: yes
  yum:
    name: golang
    state: present

- name: Set path of Golang 1
  become: yes
  template:
    src: go.sh
    dest: /etc/profile.d/go.sh
    force: no

- name: Set path of Golang 2
  become: yes
  shell: source /etc/profile.d/go.sh

- name: Download beer-mug from github
  become: yes
  shell: go get github.com/misoton665/beer-mug
  environment:
    GOPATH: /root/.go
    PATH: "/root/.go/bin:{{ ansible_env.PATH }}"

- name: Install beer-mug
  become: yes
  shell: go install github.com/misoton665/beer-mug
  environment:
    GOPATH: /root/.go
    PATH: "/root/.go/bin:{{ ansible_env.PATH }}"

- name: Copy beer-mug binary to /usr/loca/bin/
  become: yes
  copy:
    src: /root/.go/bin/beer-mug
    dest: /usr/local/bin/beer-mug
    owner: root
    group: root
    mode: 0755
