- name: Check if beer-mug is installed
  command: beer-mug -h
  register: BEERMUG_INSTALLED
  ignore_errors: yes
  changed_when: false

- name: Install EPEL (Extra Packages for Enterprise Linux)
  become: yes
  yum:
    name: epel-release
    state: present
  when: BEERMUG_INSTALLED is failed

- name: Install Golang with yum
  become: yes
  yum:
    name: golang
    state: present
  when: BEERMUG_INSTALLED is failed

- name: Set path of Golang 1
  become: yes
  template:
    src: go.sh
    dest: /etc/profile.d/go.sh
    force: no
  when: BEERMUG_INSTALLED is failed

- name: Set path of Golang 2
  become: yes
  shell: source /etc/profile.d/go.sh
  when: BEERMUG_INSTALLED is failed

- name: Download beer-mug from github
  become: yes
  shell: go get github.com/misoton665/beer-mug
  environment:
    GOPATH: /root/.go
    PATH: "/root/.go/bin:{{ ansible_env.PATH }}"
  when: BEERMUG_INSTALLED is failed

- name: Install beer-mug
  become: yes
  shell: go install github.com/misoton665/beer-mug
  environment:
    GOPATH: /root/.go
    PATH: "/root/.go/bin:{{ ansible_env.PATH }}"
  when: BEERMUG_INSTALLED is failed

- name: Copy beer-mug binary to /usr/loca/bin/
  become: yes
  copy:
    src: /root/.go/bin/beer-mug
    dest: /usr/local/bin/beer-mug
    owner: root
    group: root
    mode: 0755
  when: BEERMUG_INSTALLED is failed
